### ISSUE TITLE
PHP 7.4 support is deprecated...

### ISSUE THREAD

**Issue by GwynethLlewelyn** [kiler129/math-set#1]
... so would you consider making whatever changes are necessary for the 8.X branch?

Probably the answer is 'none' — your `composer.json` just needs to allow installation under PHP 8.X.

Thanks in advance!

**Comment by kiler129** [comment]
Hi!

I think https://github.com/kiler129/math-set/commit/a6851f973ca857046985f13b2cf7b1b430150de4 should solve the issue :)

**Comment by GwynethLlewelyn** [comment]
Oh... yay! Thanks so much :-) Wow, that _was_ **fast**!
